from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from brp.bewoning_api.models.base_model import Model
from brp.bewoning_api.models.bewoning import Bewoning
from brp.bewoning_api import util

from brp.bewoning_api.models.bewoning import Bewoning  # noqa: E501

class BewoningenQueryResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, bewoningen=None):  # noqa: E501
        """BewoningenQueryResponse - a model defined in OpenAPI

        :param bewoningen: The bewoningen of this BewoningenQueryResponse.  # noqa: E501
        :type bewoningen: List[Bewoning]
        """
        self.openapi_types = {
            'bewoningen': List[Bewoning]
        }

        self.attribute_map = {
            'bewoningen': 'bewoningen'
        }

        self._bewoningen = bewoningen

    @classmethod
    def from_dict(cls, dikt) -> 'BewoningenQueryResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BewoningenQueryResponse of this BewoningenQueryResponse.  # noqa: E501
        :rtype: BewoningenQueryResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bewoningen(self) -> List[Bewoning]:
        """Gets the bewoningen of this BewoningenQueryResponse.


        :return: The bewoningen of this BewoningenQueryResponse.
        :rtype: List[Bewoning]
        """
        return self._bewoningen

    @bewoningen.setter
    def bewoningen(self, bewoningen: List[Bewoning]):
        """Sets the bewoningen of this BewoningenQueryResponse.


        :param bewoningen: The bewoningen of this BewoningenQueryResponse.
        :type bewoningen: List[Bewoning]
        """

        self._bewoningen = bewoningen
