from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from brp.bewoning_api.models.base_model import Model
import re
from brp.bewoning_api import util

import re  # noqa: E501


class Naam(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, volledige_naam=None):  # noqa: E501
        """Naam - a model defined in OpenAPI

        :param volledige_naam: The volledige_naam of this Naam.  # noqa: E501
        :type volledige_naam: str
        """
        self.openapi_types = {"volledige_naam": str}

        self.attribute_map = {"volledige_naam": "volledigeNaam"}

        self._volledige_naam = volledige_naam

    @classmethod
    def from_dict(cls, dikt) -> "Naam":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Naam of this Naam.  # noqa: E501
        :rtype: Naam
        """
        return util.deserialize_model(dikt, cls)

    @property
    def volledige_naam(self) -> str:
        """Gets the volledige_naam of this Naam.

        Combinatie van predicaat, voornamen, adellijke titel, voorvoegsels en geslachtsnaam, zonder toevoeging van een eventuele partnernaam.   # noqa: E501

        :return: The volledige_naam of this Naam.
        :rtype: str
        """
        return self._volledige_naam

    @volledige_naam.setter
    def volledige_naam(self, volledige_naam: str):
        """Sets the volledige_naam of this Naam.

        Combinatie van predicaat, voornamen, adellijke titel, voorvoegsels en geslachtsnaam, zonder toevoeging van een eventuele partnernaam.   # noqa: E501

        :param volledige_naam: The volledige_naam of this Naam.
        :type volledige_naam: str
        """
        if volledige_naam is not None and not re.search(
            r"^[a-zA-Z0-9À-ž \.\-\']{1,450}$", volledige_naam
        ):  # noqa: E501
            raise ValueError(
                r"Invalid value for `volledige_naam`, must be a follow pattern or equal to `/^[a-zA-Z0-9À-ž \.\-\']{1,450}$/`"
            )  # noqa: E501

        self._volledige_naam = volledige_naam
